import TitleBar from "@/components/TitleBar";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TitleBar title="Todo List" />
        {children}
      </body>
    </html>
  );
}